### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by macmanes** [cboursnell/transfuse#5]
do I need Ruby 2.X?
```
$ sudo gem install transfuse
[sudo] password for macmanes:
Fetching: trollop-2.1.2.gem (100%)
Fetching: bindeps-1.2.0.gem (100%)
Fetching: bio-1.5.0.gem (100%)
Fetching: crb-blast-0.6.6.gem (100%)
Fetching: fix-trinity-output-1.0.0.gem (100%)
Fetching: colorize-0.7.7.gem (100%)
Fetching: transrate-1.0.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing transfuse:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:2:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/transrate-1.0.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/transrate-1.0.1/ext/transrate/gem_make.out
```

**Comment by macmanes** [comment]
nevermind. the answer is yes.
