### ISSUE TITLE
Salmon failure

### ISSUE THREAD

**Issue by arvindsundaram** [cboursnell/transfuse#7]
I am trying to merge 4 different assemblies and got an error from Salmon. I have attached the logs as well as standard error with this message. Hope you can spot the issue and provide me a solution for it. 
And I would also like to specify 'strandedness' for Salmon - Is this possible?

[transfuse.merge_norm2.txt](https://github.com/cboursnell/transfuse/files/202689/transfuse.merge_norm2.txt)

Thanks.

**Comment by aaronk** [comment]
We are also having salmon trouble, but it looks like we're using a newer version of transrate perhaps?

```
Freeing memory used by read queue . . .
Joined parsing thread . . . "/n/regal/oconnell_lab/loconnell/toxcomb/normtrans/transrate_Binpacker/compiled_R2_pair.fq.normalized_K25_C30_pctSD200.fq.compiled_R2_pair.fq.normalized_K25_C30_pctSD200.fq.Binpacker.bam"
Closed all files . . .
Emptied frag queue. . .
Emptied Alignemnt Group Pool. .
Emptied Alignment Group Queue. . . done
============
Exception : [Error in function boost::math::digamma<double>(double): numeric overflow]
============
/n/sw/fasrcsw/apps/Core/transrate/1.0.1-fasrc01/bin/salmon alignment-quant was invoked improperly.
For usage information, try /n/sw/fasrcsw/apps/Core/transrate/1.0.1-fasrc01/bin/salmon quant --help-alignments
Exiting.

/n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transrate-1.0.1/lib/transrate/salmon.rb:27:in `run': Salmon failed (Transrate::SalmonError)
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transrate-1.0.1/lib/transrate/read_metrics.rb:120:in `assign_and_quantify'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transrate-1.0.1/lib/transrate/read_metrics.rb:63:in `run'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transrate-1.0.1/lib/transrate/transrater.rb:86:in `read_metrics'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/lib/transfuse/transfuse.rb:228:in `block (2 levels) in transrate'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/lib/transfuse/transfuse.rb:224:in `chdir'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/lib/transfuse/transfuse.rb:224:in `block in transrate'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/lib/transfuse/transfuse.rb:220:in `each'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/lib/transfuse/transfuse.rb:220:in `each_with_index'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/lib/transfuse/transfuse.rb:220:in `transrate'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/gems/transfuse-0.5.0/bin/transfuse:66:in `<top (required)>'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/bin/transfuse:23:in `load'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/bin/transfuse:23:in `<main>'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
       from /n/home00/loconnell/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'
(END)
```

**Comment by 000generic** [comment]
I'm getting a Salmon error similar to aaronk - I'm running  transfuse 0.5.0 with packaged transrate 1.0.1 and packaged salmon 0.4.2. 

Please see attached file for log.  

[transfuse-log.txt](https://github.com/cboursnell/transfuse/files/800440/transfuse-log.txt)

**Comment by cboursnell** [comment]
I've not seen that error from salmon before. It looks like you're using all the versions that I have tested transfuse with. This error is happening when `transrate` is running analysis on the bam files that are produced by `snap`. 

If you run salmon_v0.4.2 standalone on that bam file do you get the same error?

This is the command that transrate uses:
```
salmon quant --libType IU --alignments <bamfile> --targets <assembly> --threads <threads> --sampleOut --sampleUnaligned --output . --useVBOpt --useErrorModel
```

**Comment by jdmontenegro** [comment]
Hello all,

Has this issue been resolved? I am running into a similar error. Apparently Salmon is unable to map the reads back to the assemblies and therefore gets a count of 0 for every transcript, that is what triggers the boost library error, but I do not know how to solve it. Any suggestions would be very welcome.

**Comment by xibalbanus** [comment]
Good day,

I am having the same issue with the latest transfuse release. Any ideas?

Cheers,

J.

**Comment by webbchen** [comment]
I've come across the same error message displayed by @aaronk, but only with my latest attempt of fusing several assemblies from multiple assemblers. All previous runs with smaller batches of assemblies worked fine.

**Comment by webbchen** [comment]
Update on the salmon failure: The issue has been brought up and worked around in salmon itself, see:
[https://github.com/COMBINE-lab/salmon/issues/48](url)

About halfway down, user rob-p comments on it and recommends leaving out the  `--useVBOpt` option. 

To do that in transfuse I went here: /my/path/to/transfuse-0.5.0-linux-x86_64/lib/ruby/2.2.0/gems/transrate-1.0.1/lib/transrate/ .
In this directory lives a file called salmon.rb and in there below the line

`    def build_command assembly, bamfile, threads=4`
I removed the line
`      cmd << " --useVBOpt"`

and the problem went away.
